### ISSUE TITLE
Is broken fix please

### ISSUE THREAD

**Issue by jagibson** [danrue/gluster_stats#8]

**Comment by jagibson** [comment]
Update:  I am using python

**Comment by jagibson** [comment]
and gluster

**Comment by danrue** [comment]
How's it going @jagibson! I'm really hoping you're not using this :-)

**Comment by jagibson** [comment]
Yay you saw me!

It's going good.  I was trying to fix the monitoring on an old gluster cluster but this code didn't want to work.  I intended to send you a PR once I got it fixed but other things got in the way and I haven't worked on it. (shrugs)

**Comment by jagibson** [comment]
Aaaaand I just looked around and couldn't find where I was testing so I really don't have any useful debugging info for you.  Closing.
